version: '2.1'
services:
  app:
    image: libertyapp:1.0-SNAPSHOT
    container_name: app
    networks:
      libertynet:
          aliases:
            - app
    environment:
      HOST_BANCO: banco
      HOST_MQ: mq
    depends_on:
      banco:
        condition: service_healthy
      mq:
        condition: service_healthy
    links:
     - banco
     - mq
  banco:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      libertynet:
        aliases:
          - banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: xauser
      POSTGRES_DB: xadb
  mq:
    image: ibmcom/mq
    container_name: mq
    networks:
      libertynet:
        aliases:
          - mq
    healthcheck:
      test: ["CMD-SHELL", "dspmq|grep Running && echo 0 || echo 1"]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      LICENSE: 'accept'
      MQ_QMGR_NAME: 'QM1'

networks:
  libertynet: